[package]
name = "advent-of-code-2016"
version = "0.1.0"
authors = ["Arion Roberto Krause <arionkrause@gmail.com>"]
edition = "2018"

[dependencies]
num_cpus = "1.10.0"
rayon = "1.0.3"
regex = "1.1.0"
rust-crypto = "0.2.36"
